steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chat-service', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chat-service']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'chat-service',
        '--image',
        'gcr.io/$PROJECT_ID/chat-service',
        '--platform',
        'managed',
        '--region',
        'us-central1',
        '--allow-unauthenticated',
        '--env-vars-file',
        '.env.yml',
      ]
