/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Secure Chat API
 * The Secure Chat API description
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  email: string;
  name: string;
  password: string;
  publicKey: string;
}
