/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Secure Chat API
 * The Secure Chat API description
 * OpenAPI spec version: 1.0
 */

export interface User {
  id: string;
  email: string;
  name: string;
  publicKey: string;
  createdAt: string;
  updatedAt: string;
}
